### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by zoey-on-github** [zoey-on-github/deepthroat.js#2]
I find it a bit weird im saying this on *this* repo of all places, but there's a vulnerability in this stemming from the way I handled the toJson method [[](https://nitter.fdn.fr/1lexxi/status/1582631132176461824#m)](https://twitter.com/1lexxi/status/1582631132176461824#m)

I have acess to github rn but not a cli meaning I can't fully fix it rn but I felt it was worth noting it here just so yall would know

**Comment by zoey-on-github** [comment]
fixed in #3

**Comment by ghost** [comment]
My hubris has caught up to me
